matrix:
  include:
    - os: linux
      dist: trusty
      php:
        - '5.4'
        - '5.5'
    - os: linux
      dist: xenial
      php:
        - '5.6'
        - '7.0'
        - '7.1'
        - '7.2'
        - '7.3'

language: php

sudo: false

before_script:
  - composer self-update && composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml.dist

after_success:
  - travis_retry php vendor/bin/coveralls
